packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@iconify-json/mdi': ^1.2.3
  '@unocss/nuxt': 66.1.0-beta.7
  '@unocss/preset-icons': 66.1.0-beta.7
  '@vueuse/core': ^13.0.0
  nuxt: ^3.14.1592
  unocss: 66.1.0-beta.7
  vue: ^3.5.13
  vue-router: ^4.5.0
catalogs:
  cli:
    '@antfu/eslint-config': ^4.11.0
    bumpp: ^10.1.0
    eslint: ^9.23.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.4
  testing:
    vitest: ^3.1.1
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.1
  types:
    '@types/node': ^22.13.10
  utils:
    gifuct-js: ^2.1.2
    tinyexec: ^0.1.3-beta.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
